### ISSUE TITLE
Password issue when refreshing Sentinels

### ISSUE THREAD

**Issue by boliv** [redis-rb/redis-client#107]
Hi,
I have Redis Sentinels running with Docker compose and a password is required to authenticate with those sentinels.
I have noticed that when redis-client is refreshing the sentinels, the password does not persist.
I end up with sentinels that are missing the command AUTH which I believe is the reason why I am getting in my logs the error message "NOAUTH HELLO must be called with the client already authenticated".
Is this behavior expected ? Am I missing something ?
Thanks

PS: The issue started happening from version v0.14.0 and the introduction of the [refresh_sentinels](https://github.com/redis-rb/redis-client/blob/e9f27076f4c41b51775239fb0ffa5011130fe1a5/lib/redis_client/sentinel_config.rb#L115) method.

**Comment by casperisfine** [comment]
Yep, that's a bug. I'll try to find a fix.

**Comment by casperisfine** [comment]
Hum, can you show me how you create the sentinel client (with redacted passwords of course)? Looking at the code I think it should work.

**Comment by byroot** [comment]
What if you do:

```ruby
{
  name: "mymaster",
  sentinels: [ { host: "headless-redis.default.svc.cluster.local", port: 26379 } ],
  password: "xxxxxxxx",
}
```

**Comment by casperisfine** [comment]
@boliv would you mind trying that branch: https://github.com/redis-rb/redis-client/pull/110

I believe it fixes the bug, but it's quite hard to test for so I'd appreciate if you could confirm it works before I cut a new release.

**Comment by boliv** [comment]
Hi @casperisfine,
Thanks for the update, however now the sentinels are getting all the redis client config such as database selection which ends up in the connection_prelude of the sentinels. This throws a RedisClient::CommandError. I guess only the password needs to be provided to the sentinels.

**Comment by casperisfine** [comment]
Arf, I need to dig a bit deeper into this. I need to review all the options and see which ones make sense for sentinel and which ones don't.

**Comment by casperisfine** [comment]
Ok, I think only `db` is really a problem. I updated the PR.

**Comment by boliv** [comment]
Hi @casperisfine, I tested the updated PR and It looks like it's fixed now.
Thanks.
