### ISSUE TITLE
Command Builder does not handle Big Decimal.

### ISSUE THREAD

**Issue by hewrin** [redis-rb/redis-client#109]
When passing in a BigDecimal to the command,I get a `TypeError  "Unsupported command argument type: BigDecimal"` error.

Not sure if its a big deal as I can cast it to a float or an int before passing it in, but I have attempted a fix in #108

Thanks!

**Comment by casperisfine** [comment]
Thanks for the PR, but this is by design: https://github.com/redis-rb/redis-client#type-support

`redis-client` tries to only accept types that are supported by the protocol.

**Comment by hewrin** [comment]
I see, I missed that part. Sorry!
