### ISSUE TITLE
Using Action Cable with redis-client

### ISSUE THREAD

**Issue by cirdes** [redis-rb/redis-client#111]
Hi,

I'm trying to use redis-client instead of redis with Action Cable but I'm getting the erro "Error loading the 'redis' Action Cable pubsub".

It's seems that Action Cable doesn't work with the default "redis" adaptar for Action Cable.

I have to use redis for Action Cable and redis-client for sidekiq or anyone is running redis-client for both?

ps: Sorry if here is not the right place for this kind of issue

**Comment by casperisfine** [comment]
That's not possible. That would require a change on the Active Support side (which I may do at some point but I didn't yet).

Either way, that would be a feature request for Active Support, not for redis-client.
