### ISSUE TITLE
ArgumentError(unknown keyword: :scheme)

### ISSUE THREAD

**Issue by n-rodriguez** [redis-rb/redis-client#114]
Hi there!

I've update `redis` gem to `5.0.6` and now I get this error :

**Comment by byroot** [comment]
Yes it was removed in redis-rb 5.x, just use `ssl: true/false` instead.

**Comment by n-rodriguez** [comment]
> Yes it was removed in redis-rb 5.x, just use `ssl: true/false` instead.

Without deprecation cycle?

**Comment by n-rodriguez** [comment]
Gems that depend on `redis` are also broken : https://github.com/redis-store/redis-store/issues/358#issuecomment-1446489751

**Comment by n-rodriguez** [comment]
I tought we could handle the deprecation here : https://github.com/redis-rb/redis-client/blob/master/lib/redis_client/config.rb#L170 but it might be a bit late.
