### ISSUE TITLE
ArgumentError:               unknown keywords: :io_threads_active, :appendonly, :maxmemory, :save

### ISSUE THREAD

**Issue by nazargulov** [redis-rb/redis-client#149]
I have custom options for redis settings:
```
  io_threads_active: yes  # Enable IO threads for read operations
  appendonly: no          # Enable AOF
  maxmemory: 1GB           # Set the maximum memory limit
  save: "" # Disable RDB snapshots
```
How can I pass them on?

**Comment by casperisfine** [comment]
These are server settings. They go in the server config file. This repo is a client library.

**Comment by casperisfine** [comment]
Or you can set them using the `CONFIG SET` command: https://redis.io/commands/config-set/, but it's best to use the config file.
