### ISSUE TITLE
Monitoring and observability

### ISSUE THREAD

**Issue by mperham** [redis-rb/redis-client#15]
The next big issue I can think of for adoption will be metrics and observability. There are lots of gems and APMs which patch into the Redis client in order to monitor usage and track app performance.

Here's AppSignal's hook:

https://github.com/appsignal/appsignal-ruby/blob/main/lib/appsignal/hooks/redis.rb

Here's Skylight's:

https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/probes/redis.rb

Is compatibility possible or worthwhile? Do you have or want to provide a public hook point for APMs?

**Comment by casperisfine** [comment]
> Do you have or want to provide a public hook point for APMs?

Yes, that's pretty much my next objective (this week-ish). We make heavy use of https://github.com/Shopify/semian, and for the most part it has to rely on fragile monkey patches. I'd like to introduce a clean and stable API for monitoring and such.
