### ISSUE TITLE
Provide invalid command in error

### ISSUE THREAD

**Issue by mperham** [redis-rb/redis-client#20]
```
RedisClient::CommandError: ERR syntax error
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client/connection_mixin.rb:9:in `call'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client.rb:177:in `block (2 levels) in call'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client/middlewares.rb:8:in `call'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client.rb:176:in `block in call'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client.rb:506:in `ensure_connected'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client.rb:175:in `call'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client.rb:475:in `scan_list'
    /Users/mperham/.gem/ruby/3.0.3/gems/redis-client-0.4.0/lib/redis_client.rb:224:in `scan'
    /Users/mperham/src/ent/lib/sidekiq-ent/limiter/status.rb:25:in `each'
```

I'd like to see the actual command that generated this error, similar to a compiler emitting the line of code which generated an error. Since you are processing the response, you should have the request context. Can you include the line that was sent to Redis?

**Comment by casperisfine** [comment]
Interesting feature. It's certainly doable, but I'm a bit worried about the extra complexity for pipelines. Best way to know is to try to implement it.

**Comment by mperham** [comment]
Fair. Since redis-client nudges the user to build their own Redis commands with `call("foo", "bar", etc...)`, it's very useful to see the fully constructed command in order to determine the bug in command construction.

**Comment by casperisfine** [comment]
> it's very useful to see the fully constructed command in order to determine the bug in command construction.

Agreed.
