### ISSUE TITLE
RedisClient::ReadTimeoutError: Waited 4.0 seconds

### ISSUE THREAD

**Issue by tuanbht** [redis-rb/redis-client#202]
Hi forks,
I am using redis-client latest version but still keep getting this error. Is that fixed in the latest?
Or how I can workaround for that now? It's just annoying 

<img width="627" alt="Screenshot 2024-06-18 at 08 33 26" src="https://github.com/redis-rb/redis-client/assets/56242492/c7ab204a-eccc-4f26-9e6b-77169b74d8f2">

**Comment by stanhu** [comment]
Are you using Sidekiq? See https://github.com/sidekiq/sidekiq/issues/6162.

**Comment by tuanbht** [comment]
oh, I see. Thanks a lot @stanhu
