### ISSUE TITLE
Provide URL getter

### ISSUE THREAD

**Issue by mperham** [redis-rb/redis-client#22]
It's really useful to be able to see a URL of the configured Redis client. For instance, the footer of the Sidekiq Web UI shows the active Redis URL. Rather than Sidekiq piecing it together, would it make sense to have a `RedisClient::Config#url` method?

**Comment by mperham** [comment]
Example: `rediss://localhost:6379/14`. I'm ok with it returning a URI or String.

**Comment by casperisfine** [comment]
Interesting, I think it's worth looking at it, I just want to be careful not to expose something I'll regret, as in `redis-rb` URL management was a major pain point.

Couple open question:

  - Should that method directly return the URL it received if it did? Or Should it always reconstruct it?
  - Should the URL contain the password? That could cause it to be leaked. But you can already access `Config#password` so...

**Comment by casperisfine** [comment]
Additional question after starting to implement:

What to return for `path / unix socket` connections? `redis-rb` does this thing with the `unix:` schemes but, It's entirely made up that scheme isn't registered anywhere nor understood by `redis-cli`. The `redis://` scheme has no provision for local sockets: https://www.iana.org/assignments/uri-schemes/prov/redis

**Comment by casperisfine** [comment]
Ok, so the implementation `sidekiq-web` currently depends on is 👍 

```ruby
      Sidekiq.redis do |conn|
        conn.connection[:id]
      end
```

Which is very much just:

```ruby
    def id
      @options[:id] || "#{@options[:ssl] ? 'rediss' : @options[:scheme]}://#{location}/#{db}"
    end
```

I think this makes sense as an identifier for the server itself, so no username, no password etc. I'm just not sure we should call it URL as it would confuse users into thinking they'd get the full URL the passed back.

We can't re-use `id` either because that's what's used for `CLIENT SETNAME`. Maybe `server_url` ?

**Comment by mperham** [comment]
I'm fine with `server_url`. I think `id` should only be the client's setname value.

**Comment by mperham** [comment]
Don't include the password; I'm displaying the value of `server_url`.

I've seen `unix:/var/run/redis.sock` but didn't know it was unofficial.
