### ISSUE TITLE
unknown keyword: :region

### ISSUE THREAD

**Issue by eileen-jiang** [redis-rb/redis-client#220]
We are currently using the Redis gem and are switching over to `redis-client 0.22.2`. On app bootup, we're getting an error `unknown keyword: :region`.

I see that `region` isn't supported in the README's `Configuration` [section](https://github.com/redis-rb/redis-client?tab=readme-ov-file#configuration). Is there an alternative?

If it matters, here are the other options we're passing into config:
```
{ :size=>15, 
  :pool_name=>"internal", 
  :db=>5, 
  :host=>"...usw2.cache.amazonaws.com", 
  :port=>6379, 
  :timeout=>5.0, 
  :password=>"REDACTED", 
  :region=>"us-west-2", 
  :ssl=>true, 
  :username=>"app", 
  :url=>nil }
```

**Comment by byroot** [comment]
`region` was never a supported keyword in any of the `redis` versions, it's just that redis 4.x would just ignore unknown keywords, and 5.x now only accept known ones. This is to catch typoes and such early.

Just remove that parameter and you'll be fine.
