### ISSUE TITLE
Is there way to add some commands to connection prelude?

### ISSUE THREAD

**Issue by supercaracal** [redis-rb/redis-client#25]
Hello,

I'm implementing [a cluster client](https://github.com/redis-rb/redis-cluster-client) with `RedisClient`. The cluster client needs to call the [READONLY](https://redis.io/commands/readonly/) command at connection prelude if we use the scale reading feature of cluster mode. Is there way to add some commands to the prelude without method overriding?

https://github.com/redis-rb/redis-client/blob/f85e2a8c172a512e5c92dac52e6fed6e1f641d52/lib/redis_client/config.rb#L95-L107
https://github.com/redis-rb/redis-client/blob/f85e2a8c172a512e5c92dac52e6fed6e1f641d52/lib/redis_client.rb#L551-L582

**Comment by byroot** [comment]
Not at the moment, but it could make sense to have a `prelude:` parameter for `Config`. Feel free to PR that.

But also subclassing `Config` may make sense, that's that I do for sentinel. But up to you.

**Comment by supercaracal** [comment]
Thank you for your quick reply. I'll try to override with subclassing because this issue is cluster mode matter.
