### ISSUE TITLE
About error handling of pipelining

### ISSUE THREAD

**Issue by supercaracal** [redis-rb/redis-client#28]
Hello,

Since pipelining is a bulk processing, probably, there might be a use case to want to handle errors by caller-side. I'm not sure yet either `RedisClient#pipelined` method should raise the first error or not.

In case of `redis-cluster-client`, the client should handle errors of `MOVED` and `ASK` redirection in pipeline. Of course it is a matter of the cluster client, so it can be implemented with overwriting or a dedicated method. But I'd say that it would be better to have the same behavior between `RedisClient` and `RedisClient::Cluster`.

What are your thoughts on this?

```ruby
cli = RedisClient.config.new_client
replies = cli.pipelined do |pi|
  # pi.call('something')
end

# Case: 1
errors = replies.select { |reply| reply.is_a?(RedisClient::Error) }
raise MyError, errors.map(&:message) unless errors.empty?

# Case: 2
replies.each_with_index do |reply, i|
  if reply.is_a?(RedisClient::Error)
    # do something
  else
    # do something
  end
end
```

```
$ (printf "PING\r\nPANG\r\nPING\r\nQUIT\r\n"; sleep 0.1) | nc 127.0.0.1 6379
+PONG
-ERR unknown command 'PANG', with args beginning with:
+PONG
+OK
```

```
irb(main):001:0> cli = RedisClient.config.new_client
=> #<RedisClient redis://localhost:6379/0>

irb(main):005:1* cli.pipelined do |pi|
irb(main):006:1*   pi.call('PING')
irb(main):007:1*   pi.call('PANG')
irb(main):008:1*   pi.call('PING')
irb(main):009:1*   pi.call('QUIT')
irb(main):010:0> end
/home/kasuga/vcs/redis-client/lib/redis_client/connection_mixin.rb:34:in `call_pipelined': ERR unknown command 'PANG', with args beginning with:  (RedisClient::CommandError)
        from /home/kasuga/vcs/redis-client/lib/redis_client.rb:287:in `block (2 levels) in pipelined'
        from /home/kasuga/vcs/redis-client/lib/redis_client/middlewares.rb:8:in `call'
        from /home/kasuga/vcs/redis-client/lib/redis_client.rb:286:in `block in pipelined'
        from /home/kasuga/vcs/redis-client/lib/redis_client.rb:520:in `ensure_connected'
        from /home/kasuga/vcs/redis-client/lib/redis_client.rb:284:in `pipelined'
        from (irb):5:in `<main>'
        from bin/console:8:in `<main>'
```

https://github.com/redis-rb/redis-client/blob/dcd7f3dc6f2cc1c652fd2bcc914e8034d6cf074f/lib/redis_client/connection_mixin.rb#L16-L38

**Comment by byroot** [comment]
Hum. What about passing it as an option to `pipelined` ? e.g. `pipelined(raise: false)`?

**Comment by supercaracal** [comment]
I think it's better. :+1:

**Comment by byroot** [comment]
I’m AFK so just brain dumping quickly: ASK and MOVED should also not be CommandError subclasses. Not even sure they should be errors at all

**Comment by supercaracal** [comment]
Certainly. They are not `5xx` but `3xx` in the HTTP world. 🤔

**Comment by supercaracal** [comment]
On a second thought, I thought it should be realized with override in cluster client. Thank you for your advices.
