### ISSUE TITLE
Allow subclasses of String as values.

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [redis-rb/redis-client#51]
I have encountered this error using Redis 5.x, which uses redis-client. Which I think could pop up in several compatibility issues (https://github.com/redis/redis-rb/issues/1142).

     Failure/Error: redis.setex key, TTL, value
     
     TypeError:
       Unsupported command argument type: ActiveSupport::SafeBuffer

I would expect a subclass of String to be ok, to pass as a value. But the redis-client gem that redis uses in 5.x is very strict.
Instead of
```
case value
when String
end
```
It does
```
method = DUMP_TYPES.fetch(object.class) do
  raise TypeError, "Unsupported command argument type: #{object.class}"
end
```

Consider whether the type checking is too strict.

**Comment by byroot** [comment]
That's fair. We can accept subclasses.
