### ISSUE TITLE
Question about redis/redis-rb vs redis-rb/redis-client

### ISSUE THREAD

**Issue by jmthomas** [redis-rb/redis-client#57]
@byroot I'm confused as to what is happening with redis/redis-rb and this repo. You've been very active in the redis/redis-rb repo implementing these clients as the real clients in the redis gem. I'm wondering if it makes sense to completely switch to redis-client and redis-cluster-client from redis-rb and redis-clustering. Can you provide some guidance on the differences between the two and the future of the Ruby clients? Thanks for all your work!

**Comment by byroot** [comment]
👋 there's a breakdown of the relation between the two and the future plans in https://github.com/redis/redis-rb/issues/1070

In short, I definitely recommend switching to raw `redis-client` if that suits your use case and that your Redis supports it (there are a bunch of Redis proxies out there that don't support RESP3).

For now `redis-rb` uses `redis-client` as its transport layer, but keep using the RESP2 protocol and doing lots of type casting. Once I feel like the various redis providers out there generally support RESP3, I'll probably work on `redis-rb 6.0` which will drop all that type casting and be a very small layer on top of `redis-client`.

Hope it answers your question.
