### ISSUE TITLE
Add common convenience methods

### ISSUE THREAD

**Issue by jcraigk** [redis-rb/redis-client#63]
Similar to the https://github.com/redis/redis-rb gem, it would be very helpful to add common (or all) Redis keyword calls, so instead of `redis.call('SET', 'foo', 'bar')`, we could call `redis.set('foo', 'bar')`.

**Comment by byroot** [comment]
The whole point of this library is not to do that.

**Comment by byroot** [comment]
Eventually you can do this: https://github.com/mperham/sidekiq/blob/0e91f175fe8ada215bcf64bb086ca7585fe60e3f/lib/sidekiq/redis_client_adapter.rb#L22-L34
