### ISSUE TITLE
Attempt Reconnect on Redis::CommandError (Elasticache failover)

### ISSUE THREAD

**Issue by tylerbrewer2** [redis-rb/redis-client#69]
Hello!

I'm digging into some process crashes after an Elasticache failover. It appears as if a `READONLY You can't write against a read only replica. (Redis::CommandError)` error is returned after the failover. I _believe_ this is because redis-client is still connected to the old primary node instead of the new primary node.

Is there a way to reset connection after a command error? Looking [here](https://github.com/redis-rb/redis-client/blob/master/lib/redis_client.rb#L626), it looks like only `ConnectionError` and `ProtocolError` is handled, which I'm sure is for a very good reason.

Apologies if my assumptions are wrong here and I'm misreading the code. Thanks for the library!

**Comment by byroot** [comment]
As of https://github.com/redis-rb/redis-client/pull/65 (released as `0.11.2`), `READONLY` are treated as ConnectionError.

So this is handled now.

I still need to update the error in `redis-rb` though: https://github.com/redis/redis-rb/blob/fe90f6d2dc4fd822cc45fb3809529334bae420fa/lib/redis/errors.rb#L29

**Comment by tylerbrewer2** [comment]
Awesome, thank you!

I went ahead and opened a [PR](https://github.com/redis/redis-rb/pull/1168). I believe most of the logic related to this change lives in this repo (I could be, and likely am, wrong).
