### ISSUE TITLE
command_builder should should allow SADD to pass an array as an argument

### ISSUE THREAD

**Issue by jpaas** [redis-rb/redis-client#76]
Using 0.11.2 when using the `SADD` command, if I pass an array as an argument I get this error: Unsupported command argument type: Array because he argument validation in command_builder does not allow this.

Fix is trivial. PR to follow.

**Comment by casperisfine** [comment]
Would you mind showing the code that cause this error?

**Comment by casperisfine** [comment]
```ruby
>> RedisClient.new.call("SADD", "set", ["a", "b"])
=> 2
```

The above works just fine, so I assume you have deeply nested arrays? If so they're rejected on purpose.

**Comment by jpaas** [comment]
Its coming from `sidekiq-batch` on this line
https://github.com/breamware/sidekiq-batch/blob/master/lib/sidekiq/batch.rb#L99

**Comment by casperisfine** [comment]
Yup, they should flatten that.

The reason I don't want to allow nested arrays is that most of the time it's not intended. `redis-client` tries to be strict to avoid silent issues.

**Comment by jpaas** [comment]
Thanks @casperisfine. I'll take this up with `sidekiq-batch`
