### ISSUE TITLE
Hiredis "Unknown Timeout"

### ISSUE THREAD

**Issue by yosiat** [redis-rb/redis-client#81]
Hi,

Since upgrading to redis-client from the oldest one, I am starting to get `Redis::TimeoutError:  Unknown Error` while using hiredis-client.

I saw in the documentation: 
```
Contrary to the redis gem, redis-client doesn't protect against concurrent access. To use redis-client in concurrent environments, you MUST use a connection pool, or have one client per Thread or Fiber.
```

My rails app is running in multi-threaded Puma app, the question - is the comment about concurrency is relevant to hiredis-client as well?

Thanks

**Comment by casperisfine** [comment]
Please include the full backtrace otherwise it's hard to debug this.

> is the comment about concurrency is relevant to hiredis-client as well?

Yes. The simplest is to use a connection pool: https://github.com/redis-rb/redis-client#usage

**Comment by yosiat** [comment]
The stack is:
```
/gems/hiredis-client-0.12.0/lib/redis_client/hiredis_connection.rb:74 in _read
/gems/hiredis-client-0.12.0/lib/redis_client/hiredis_connection.rb:74 in read
/gems/redis-client-0.12.0/lib/redis_client/connection_mixin.rb:18 in call
/gems/redis-client-0.12.0/lib/redis_client.rb:225 in block (2 levels) in call_v
/gems/redis-client-0.12.0/lib/redis_client/middlewares.rb:16 in call
```

But can it be I am getting timeouts, because I am not using connection pool (running in 2 workers, 32 threads) ?

**Comment by yosiat** [comment]
Gotcha, thanks!

Currently I am using `Redis.new(..)` I'll change it to connection pool suggested from the document, I assume that when I use `RedisClient` behind the scenes it will use hiredis as driver (if I chosen so)

**Comment by casperisfine** [comment]
> Currently I am using Redis.new(..) 

If you are still using `redis-rb`, you are protected by a Mutex. It's incredibly wasteful because your 32 threads will fight for the lock, but it shouldn't cause errors.

**Comment by yosiat** [comment]
Gotcha, so I will use `ConnectionPool::Wrapper` as suggested here - https://github.com/redis/redis-rb#connection-pooling-and-thread-safety

Using the pool directly with RedisClient, requires me to do lots of changes (`redis.flushdb` -> `redis.call("flushdb")` for example)

Thanks for your help!

**Comment by yosiat** [comment]
I see that we can get "Unknown Error" in multiple cases, what do you about changing it to return "Read timeout" / "Write timeout" error instead of "Unknown Error"? 

Think I can do PR for that.

**Comment by casperisfine** [comment]
I already pushed https://github.com/redis-rb/redis-client/commit/df69b9d8341957c190ed4bbd366f6fe2d0fa7cf1

**Comment by yosiat** [comment]
You are always so fast 🥇 

Umm.. but it can write timeout as well? https://github.com/redis-rb/redis-client/blob/df69b9d8341957c190ed4bbd366f6fe2d0fa7cf1/hiredis-client/ext/redis_client/hiredis/hiredis_connection.c#L669

**Comment by casperisfine** [comment]
`Timeout` is in the error class name.

**Comment by yosiat** [comment]
I understand you need a repro, sadly I can't create one - I am getting this timeout from multiple endpoints and different redis operations - it can be simple `exists?` or `mget` for multiple keys.

I am abit afraid of moving to pure redis client, because I am not sure what will be it's performance implications and I have no good way of testing it sadly.

My question about the timeout error - if we get timeout in `hiredis_read_internal` on waiting for writeable, wouldn't it be more correct to throw "write timeout" instead of `Unknown Error (hiredis_read)` ?
Asking this, because from the stack trace - 
```
/gems/hiredis-client-0.12.0/lib/redis_client/hiredis_connection.rb:74 in _read
/gems/hiredis-client-0.12.0/lib/redis_client/hiredis_connection.rb:74 in read
```

We see it's read throwing a timeout - the question is it write OR read timeout?

**Comment by byroot** [comment]
> I am abit afraid of moving to pure redis client, because I am not sure what will be it's performance implications and I have no good way of testing it sadly.

The difference really isn't that big for most response. It's only on some large array and hash responses that you can really measure it. So really don't be afraid to drop the gem for now.

**Comment by yosiat** [comment]
We have large responses in our app, anyway I'll do a change next week to have pool & way to change driver, so I can enable with ruby driver and worst case change easily to hiredis.

I'll repo back once I'll have more information, thanks for your help, really appreciated!

**Comment by byroot** [comment]
No news in a month, closing for now as non actionable. I'll reopen if I get more information
