### ISSUE TITLE
unknown keyword: :thread_safe After Upgrading to Rails 6.1

### ISSUE THREAD

**Issue by MJTM1973** [redis-rb/redis-client#85]
Hello,

I've just upgraded my app to Rails 6.1 and in the process of going through and dealing with various deprecated methods I've run into one I can't resolve.

When I run `bundle exec rspec` I'm getting an ArgumentError: `unknown keyword: :thread_safe`

From some quick googling I found out that in Rails 6.1 they removed the `after_intialize` method as that was now deprecated.

> Remove deprecated `ActiveSupport::LoggerThreadSafeLevel#after_initialize`

https://github.com/rails/rails/commit/e84af03914ff767a80fdb1a66a4dcb37f8bdb262

And since I'm getting this error on an intialize method in redis-client I figured that's where the problem lies.

![image](https://user-images.githubusercontent.com/45802269/215022214-972828ca-6af9-4bcc-9b45-e71c10891201.png)

Any thoughts on what I can look into to solve this, or if perhaps I'm misunderstanding something and am on the wrong track, would be much appreciated.

**Comment by casperisfine** [comment]
Only Resque 2.4.0 is compatible with redis-rb 5.x https://github.com/resque/resque/pull/1828
