### ISSUE TITLE
Can not pass in nil for HMSET

### ISSUE THREAD

**Issue by arianf** [redis-rb/redis-client#87]
It raises an error:
```
[4] pry(main)> RedisCache.current.hmset('foo123', 'time', Time.current.to_s, 'foo', nil)
TypeError: Unsupported command argument type: NilClass
from /usr/local/bundle/ruby/3.2.0/gems/redis-client-0.12.0/lib/redis_client/command_builder.rb:37:in `block in generate'
```

Previously:
```
Redis.current.hmset('foo123', 'time', Time.current.to_s, 'foo', nil)
=> "OK"


Redis.current.hget('foo123', 'foo')
=> ""
```

**Comment by byroot** [comment]
This is by design. Redis hash values can only be strings, you either have not to set that key, or to cast that nil to an empty string.

**Comment by arianf** [comment]
@byroot it seems interesting that we auto convert integers to strings

https://github.com/redis-rb/redis-client/blob/7897ffefb4e8d1f4926bc4ad8d718fac2a4ad02f/lib/redis_client/command_builder.rb#L34-L35

but don't do something like

```ruby
when nil then ''
```

**Comment by byroot** [comment]
Yes, because integers have an unambiguous string representation, so it's easy to know that's what the caller expects.

Casting `nil` to `""` however is super opiniated, other languages would cast it to `"null"` or something. 

Also `nil` is much more likely to be a mistake.

**Comment by arianf** [comment]
Ahh I see thanks for the explanation
