### ISSUE TITLE
Unhandled EOFError

### ISSUE THREAD

**Issue by bf4** [redis-rb/redis-client#92]
This error may be raised by [fill_buffer](https://github.com/redis-rb/redis-client/blob/d00e69821a8a1fd5dcba2e48cc010f4d97846b3d/lib/redis_client/ruby_connection/buffered_io.rb#L144-L146)

Since the Redis gem relies on RedisClient, I'd expect to have the same error raised when using Redis, but it appears that the Redis gem handles this.  I was wondering if this is a bug in the RedisClient or something undocumented which libraries using RedisClient need to handled

```ruby
redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:145 in block in fill_buffer
redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:122 in loop
redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:122 in fill_buffer
redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:114 in ensure_remaining
redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:85 in getbyte
redis-client-0.12.1/lib/redis_client/ruby_connection/resp3.rb:113 in parse
redis-client-0.12.1/lib/redis_client/ruby_connection/resp3.rb:50 in load
redis-client-0.12.1/lib/redis_client/ruby_connection.rb:123 in read
redis-client-0.12.1/lib/redis_client/connection_mixin.rb:18 in call
redis-client-0.12.1/lib/redis_client.rb:210 in block (2 levels) in call
redis-client-0.12.1/lib/redis_client/middlewares.rb:16 in call
redis-client-0.12.1/lib/redis_client.rb:209 in block in call
redis-client-0.12.1/lib/redis_client.rb:626 in ensure_connected
redis-client-0.12.1/lib/redis_client.rb:208 in call
redlock-2.0.1/lib/redlock/client.rb:172 in block (2 levels) in lock
connection_pool-2.3.0/lib/connection_pool.rb:65 in block (2 levels) in with
connection_pool-2.3.0/lib/connection_pool.rb:64 in handle_interrupt
connection_pool-2.3.0/lib/connection_pool.rb:64 in block in with
connection_pool-2.3.0/lib/connection_pool.rb:61 in handle_interrupt
connection_pool-2.3.0/lib/connection_pool.rb:61 in with
connection_pool-2.3.0/lib/connection_pool/wrapper.rb:14 in with
redlock-2.0.1/lib/redlock/client.rb:171 in block in lock
```

**Comment by byroot** [comment]
Thanks for the report, I'll have a look.

**Comment by byroot** [comment]
Hum, could you include the actual exception? Because I'm pretty sure it's handled here: https://github.com/redis-rb/redis-client/blob/c17f557329ec4b5a37d8a09d94b8f89395f2608e/lib/redis_client/ruby_connection.rb#L129 and re-raised as a `RedisClient::ConnectionError`.

The original message is preserved though.

**Comment by bf4** [comment]
you're correct that it was re-raised as a RedisClient::ConnectionError

When I went digging into where the new exception was coming from, it seems I forgot that since it didn't look like the rescue code in the relevant gem (redlock 1.3.2 -> 2.0.1) was affected

```
RedisClient::ConnectionError: EOFError
gems/redis-client-0.12.1/lib/redis_client/ruby_connection.rb:130 in rescue in read
gems/redis-client-0.12.1/lib/redis_client/ruby_connection.rb:121 in read
gems/redis-client-0.12.1/lib/redis_client/connection_mixin.rb:18 in call
gems/redis-client-0.12.1/lib/redis_client.rb:210 in block (2 levels) in call
gems/redis-client-0.12.1/lib/redis_client/middlewares.rb:16 in call
gems/redis-client-0.12.1/lib/redis_client.rb:209 in block in call
gems/redis-client-0.12.1/lib/redis_client.rb:626 in ensure_connected
gems/redis-client-0.12.1/lib/redis_client.rb:208 in call
gems/redlock-2.0.1/lib/redlock/client.rb:172 in block (2 levels) in lock
gems/connection_pool-2.3.0/lib/connection_pool.rb:65 in block (2 levels) in with
gems/connection_pool-2.3.0/lib/connection_pool.rb:64 in handle_interrupt
gems/connection_pool-2.3.0/lib/connection_pool.rb:64 in block in with
gems/connection_pool-2.3.0/lib/connection_pool.rb:61 in handle_interrupt
gems/connection_pool-2.3.0/lib/connection_pool.rb:61 in with
gems/connection_pool-2.3.0/lib/connection_pool/wrapper.rb:14 in with
gems/redlock-2.0.1/lib/redlock/client.rb:171 in block in lock
gems/redlock-2.0.1/lib/redlock/client.rb:216 in recover_from_script_flush
gems/redlock-2.0.1/lib/redlock/client.rb:170 in lock
gems/redlock-2.0.1/lib/redlock/client.rb:266 in block (2 levels) in lock_instances
gems/redlock-2.0.1/lib/redlock/client.rb:266 in select
gems/redlock-2.0.1/lib/redlock/client.rb:266 in block in lock_instances
gems/redlock-2.0.1/lib/redlock/client.rb:319 in timed
gems/redlock-2.0.1/lib/redlock/client.rb:265 in lock_instances
gems/redlock-2.0.1/lib/redlock/client.rb:240 in block in try_lock_instances
gems/redlock-2.0.1/lib/redlock/client.rb:236 in times
gems/redlock-2.0.1/lib/redlock/client.rb:236 in try_lock_instances
gems/redlock-2.0.1/lib/redlock/client.rb:69 in lock
```

**Comment by byroot** [comment]
Ok, so.. no bug?

**Comment by bf4** [comment]
So, it's definitely new behavior, and I'm not yet sure where, but yeah, closing this for now.

**Comment by bf4** [comment]
best I can figure from looking through the diff in the redlock gem and through the code in redis-client and redis is that

```diff
-        rescue Redis::CommandError => e
+        rescue RedisClient::CommandError => e
```

previously rescued a connection error as a commanderror.. but I see no evidence for that in the redis gem code.

only other thing I can guess is from a vanilla Redis.new vs. RedisClient.new confg I see

```diff
- @reconnect_attempts=[0],
+ @reconnect_attempts=false,
```

**Comment by byroot** [comment]
Ah yes, `redis-rb` attempts to reconnect once by default. It's potentially unsafe, but it has always done so, so I kept it in version 5.

`redis-client` however doesn't, and you have to specifically enable automatic retries.

**Comment by bf4** [comment]
>  It's potentially unsafe

Ah, thanks.  I've taken up enough of your time, here, but if I can help write up some "how to use transition from redis to redis-client" for downstream consumers, seems that might be a valuable section to have.  Without looking, it's not immediately clear to me why adding a default `reconnect_attempts: 1` to our redis_config would be a bad idea..

**Comment by byroot** [comment]
> it's not immediately clear to me why adding a default `reconnect_attempts: 1` to our redis_config would be a bad idea..

Yeah no worries.

The problem with retrying on error, is that you don't know if the command succeeded or not. e.g.

```ruby
redis.incr("counter") # => EOFError
```

In the above case, maybe the server processed the increment and we just failed to get the response because of a network blip. Or maybe the server never got it.

So if you enable a single retry, then:

```ruby
redis.set("counter", 0)
redis.incr("counter") # Could return either 1 or 2
```

So it's only safe to retry idempotent commands, hence why `redis-client` provides both `call` and `call_once`. Because trying to figure out whether the passed command is idempotent or not is quite a nightmare. Some commands are idempotent unless you pass a specific argument, etc.

Hope this answers your question.

**Comment by bf4** [comment]
For reference, since it may be of interest, I found related issue to the reconnect in sidekiq https://github.com/sidekiq/sidekiq/issues/3303

>       # Issue #3303, redis-rb will silently retry an operation.
>       # This can lead to duplicate jobs if Sidekiq::Client's LPUSH
>       # is performed twice but I believe this is much, much rarer
>       # than the reconnect silently fixing a problem; we keep it
>       # on by default.
>       opts[:reconnect_attempts] ||= 1
>

**Comment by byroot** [comment]
Yes, each project can make this kind of decision. Sidekiq being a job queue with "at least once" semantic, it makes sense to enable retries.

Other users may need "at most once" semantic, so as a generic library, `redis-client` doesn't chose for you.
